# To install plugins -> Press CTRL+a + shift+i

# -- General Settings ----------------------------------------------------------
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'
set -g default-terminal "screen-256color"

set -g mouse on               # Enable mouse support
set -g base-index 1           # Start windows at 1
setw -g pane-base-index 1     # Start panes at 1
set -s escape-time 0          # Faster command sequences (vital for Vim)

# -- Key Bindings --------------------------------------------------------------

# Change Prefix to Ctrl+a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Reload config file easily
bind r source-file ~/.config/tmux/tmux.conf \; display "Config Reloaded!"

# Split panes using v and s (Vim style)
bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"

# Navigate panes with Alt + hjkl (No prefix needed)
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# FIXED: Switch windows with Alt + Number (No prefix needed)
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5

# Create new window with Prefix + c
bind c new-window -c "#{pane_current_path}"

# Better "Kill" bindings
bind q kill-pane    # Prefix + q to kill a split
bind X kill-window  # Prefix + Shift + x to kill the whole tab

# -- Visuals -------------------------------------------------------------------
# set -g status-style bg=default
# set -g status-fg white
# set -g pane-active-border-style fg=green

set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.config/tmux/plugins/'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin "janoamaral/tokyo-night-tmux"
# Transparent
set -g @tokyo-night-tmux_transparent 1

set -g @tokyo-night-tmux_window_id_style none
set -g @tokyo-night-tmux_pane_id_style dsquare
set -g @tokyo-night-tmux_window_tidy_icons 0

set -g @tokyo-night-tmux_show_path 1
set -g @tokyo-night-tmux_path_format relative # 'relative' or 'full'

set -g @tokyo-night-tmux_show_git 1

set -g @plugin 'CrispyConductor/tmux-copy-toolkit'
set -g @copytk-copy-command "wl-copy"


run '~/.config/tmux/plugins/tpm/tpm'










